#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS


geometry=''  #-geometry 1280x800 
dpi=''  #'-dpi 96'

#session=startlxde
#session=startlxde
session=gnome-session
#session=startkde
#session=i3

exec dbus-launch $dpi $geometry $session
